### PR TITLE
Add a smoke test for Spring Integration

### PR DESCRIPTION
**Pull request by artembilan**
* The `jni-config.json` is added to support Netty DNS on Windows
* As well as an `--initialize-at-run-time=sun.net.dns.ResolverConfigurationImpl` in the `build.gradle`
* The channel based on the Redis with JSON serialization is commented out at the moment since
there is some deserialization regression in Spring Data Redis.
Works well with Spring Data `2022.0.0-M4`

### CODE REVIEW

**Comment by garyrussell** [comment]
>Would be great if anyone double check on other OSs.

I just ran it on MacOS (with `--include-build ../spring-integration` with your PR checked out there and I get this....

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.http.HttpStatus was unintentionally initialized at build time. To see why org.springframework.http.HttpStatus got initialized use --trace-class-initialization=org.springframework.http.HttpStatus
```

**Comment by garyrussell** [comment]
>Would be great if anyone double check on other OSs.

Solved previous noise by upgrading GraalVM from 22.1.0 to 22.2.0

Now getting
```
shouldOutputIntegrationGraph(WebTestClient, AssertableOutput)
java.lang.IllegalStateException: Timeout on blocking read for 5000000000 NANOSECONDS
```

Which, I presume, is the same error you are getting on Windows.

**Comment by artembilan** [comment]
Got it! Thanks.
And that is strange, since I have:
```
aotSmokeTest {
	webApplication = true
}
```
and I see in the `output.txt`:
```
2022-09-01T12:07:57.488-04:00  INFO 23252 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 50195
2022-09-01T12:07:57.489-04:00 DEBUG 23252 --- [           main] xIntegrationRequestMappingHandlerMapping : 1 mappings in 'webFluxIntegrationRequestMappingHandlerMapping'
2022-09-01T12:07:57.490-04:00  INFO 23252 --- [           main] c.e.integration.IntegrationApplication   : Started IntegrationApplication in 0.204 seconds (process running for 0.212)
```
So, it is definitely started on some random port, but that `WebTestClient` in the test cannot connect somehow.
Works well in JVM AOT mode though...

Without `webApplication = true` it starts on the standard `8080`, but test still cannot reach the app for some reason...

Chatted with Gary and he raised a question.
How does our application auto-configure a random port from the Redis container:
```
+---------+----------------+-----------------+
| Name    | Container Port | Mapping         |
+---------+----------------+-----------------+
| redis-1 | 6379           | localhost:57019 |
+---------+----------------+-----------------+
```
?

**Comment by wilkinsona** [comment]
The smoke test infrastructure should have set an environment variable named `REDIS_PORT_6379`. Its value will be the local port to which container port 6379 is mapped. The Data Redis smoke test makes use of this [in its application.properties](https://github.com/spring-projects/spring-aot-smoke-tests/blob/444a022915450722263b1b38a91d70fd02d28536/data-redis/src/main/resources/application.properties).

**Comment by artembilan** [comment]
Thank, Andy! That makes sense. I took docker compose config from the `session-redis-webflux`, but didn't notice that it does remapping in the code:
```
		String redisHost = System.getenv().getOrDefault("REDIS_HOST", "localhost");
		String port = System.getenv().getOrDefault("REDIS_PORT_6379", "6379");
```
😄 
Will fix respectively.

**Comment by garyrussell** [comment]
I think it would be best to use a placeholder in application.properties/yml, like here: 

https://github.com/spring-projects/spring-aot-smoke-tests/blob/444a022915450722263b1b38a91d70fd02d28536/spring-amqp-rabbit/src/main/resources/application.properties#L1-L2

**Comment by artembilan** [comment]
Even with the standard `8080` for Netty server and plain `WebClient.builder().baseUrl("http://localhost:8080").build()` in the test it cannot reach the application 😢

**Comment by artembilan** [comment]
The JVM test at that point shows these logs:
```
2022-09-01T14:01:18.154-04:00 DEBUG 32700 --- [ctor-http-nio-2] io.netty.buffer.AbstractByteBuf          : -Dio.netty.buffer.checkAccessible: true
2022-09-01T14:01:18.154-04:00 DEBUG 32700 --- [ctor-http-nio-2] io.netty.buffer.AbstractByteBuf          : -Dio.netty.buffer.checkBounds: true
2022-09-01T14:01:18.154-04:00 DEBUG 32700 --- [ctor-http-nio-2] i.n.util.ResourceLeakDetectorFactory     : Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@65d9c151
2022-09-01T14:01:18.171-04:00 DEBUG 32700 --- [ctor-http-nio-2] r.n.http.server.HttpServerOperations     : [d5015c62, L:/127.0.0.1:52999 - R:/127.0.0.1:53001] New http connection, requesting read
2022-09-01T14:01:18.171-04:00 DEBUG 32700 --- [ctor-http-nio-2] reactor.netty.transport.TransportConfig  : [d5015c62, L:/127.0.0.1:52999 - R:/127.0.0.1:53001] Initialized pipeline DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpServerCodec), (reactor.left.httpTrafficHandler = reactor.netty.http.server.HttpTrafficHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
```
I do have `NettyRuntimeHints` imported into my application.
Therefore out of ideas so far 😄

**Comment by artembilan** [comment]
OK. After some pocking around I have figured out that the problem is here:
```
Caused by: org.springframework.expression.EvaluationException: The method 'start' is not supported by this command processor. If using the Control Bus, consider adding @ManagedOperation or @ManagedAttribute.
	at org.springframework.integration.handler.ExpressionCommandMessageProcessor$ExpressionCommandMethodResolver.validateMethod(ExpressionCommandMessageProcessor.java:135) ~[na:na]
```
Need to expose reflection for those methods we can use from Control Bus.

Stay tuned.

**Comment by artembilan** [comment]
OK. Now everything works!
Broke my had to figure out that I have to use a `spring-boot-starter-data-redis-reactive` and `ReactorNettyHints` to make it working together with WebFlux 😄 

When latest Spring Integration build is green, you can review this and merge. If OK, of course.

Sorry for a noise and thank you for patience!

**Comment by wilkinsona** [comment]
@artembilan Was the latest Integration build successful? I'm seeing a failure when trying to run `nativeAotTest` on macOS:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'printFormattedSecondsFlow': Instantiation of supplied bean failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:931) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:926) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:592) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[integration:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[integration:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:430) ~[integration:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[integration:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[integration:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[integration:3.0.0-SNAPSHOT]
	at com.example.integration.IntegrationApplication.main(IntegrationApplication.java:49) ~[integration:na]
	at java.lang.Thread.run(Thread.java:833) ~[integration:na]
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705) ~[integration:na]
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
Caused by: java.lang.ExceptionInInitializerError: null
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.transform(BaseIntegrationFlowDefinition.java:729) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.convert(BaseIntegrationFlowDefinition.java:705) ~[integration:6.0.0-SNAPSHOT]
	at com.example.integration.IntegrationApplication.lambda$printFormattedSecondsFlow$4(IntegrationApplication.java:79) ~[integration:na]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.obtainInputChannelFromFlow(BaseIntegrationFlowDefinition.java:430) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.gateway(BaseIntegrationFlowDefinition.java:2171) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.integration.dsl.BaseIntegrationFlowDefinition.gateway(BaseIntegrationFlowDefinition.java:2153) ~[integration:6.0.0-SNAPSHOT]
	at com.example.integration.IntegrationApplication.printFormattedSecondsFlow(IntegrationApplication.java:79) ~[integration:na]
	at com.example.integration.IntegrationApplication__BeanDefinitions.lambda$getPrintFormattedSecondsFlowInstanceSupplier$3(IntegrationApplication__BeanDefinitions.java:97) ~[na:na]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[integration:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:210) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[integration:6.0.0-SNAPSHOT]
	... 21 common frames omitted
Caused by: java.lang.reflect.UndeclaredThrowableException: null
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147) ~[na:na]
	at org.springframework.integration.util.ClassUtils.<clinit>(ClassUtils.java:136) ~[na:na]
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.handler.GenericHandler
	at java.lang.Class.forName(DynamicHub.java:1136) ~[integration:na]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[na:na]
	at org.springframework.integration.util.ClassUtils.<clinit>(ClassUtils.java:132) ~[na:na]
	... 33 common frames omitted
```

**Comment by artembilan** [comment]
Hi, @wilkinsona, thank you for looking into this!

Not sure how you test it, I just did in the morning like this against this my PR:
```
c:\SpringIO\spring-aot-smoke-tests>gradlew clean :integration:build --refresh-dependencies
```
The result in the end is:
```
BUILD SUCCESSFUL in 4m 25s
117 actionable tasks: 38 executed, 79 up-to-date
```

Should I do it some other way?

**Comment by wilkinsona** [comment]
Thanks, Artem. Looks like `--refresh-dependencies` is what I had missed. With that in place, `nativeAotTest` succeeds on macOS.

**Comment by wilkinsona** [comment]
I'd like to wait a little while before merging this to see if https://github.com/spring-projects/spring-data-redis/pull/2397 can be merged first and we can move Boot onto Spring Data snapshots. That will remove the need for the interim runtime hints.

I also don't think the config for `sun.net.dns.ResolverConfigurationImpl` belongs in the smoke test. It should perhaps be added to the reachability metadata repository for Netty. It's hard for me to tell as no failure occurs on macOS without the config in place.

**Comment by artembilan** [comment]
Sure! We can remove that `sun.net.dns.ResolverConfigurationImpl` as well as `jni-config.json` since they are Windows-specific artifacts.
And really have to be managed from the GraalVM perspective by itself.
But the question is when that going to happen: https://github.com/oracle/graal/issues/4304 ?

At the same time we definitely have to wait for that latest change to Spring Data Redis to be merged first.

**Comment by artembilan** [comment]
Hi Andy!
Thank you for testing this!
Not sure how that `IntegrationProperties.toProperties()` had slept from my hands when I tested this, but I've now added that one as a hint: https://github.com/spring-projects/spring-integration/commit/e2a5b7d9a30ad903bc8efd2f76050e8aca85fe90.

Please, give it a retry in several minutes when fresh SNAPSHOT for Spring Integration `6.0` is available: https://build.spring.io/browse/INT-MAIN

**Comment by wilkinsona** [comment]
Thanks, @artembilan!

**Pull request closed without merging**
