### PR TITLE
Add test for result streaming with data-jpa

### PR DESCRIPTION
**Pull request by christophstrobl**
See: spring-projects/spring-data-jpa#2848

The test will fail until spring-projects/spring-data-jpa#2880 is merged to _main_ and back ported to the _3.0.x_ maintenance branch.

### CODE REVIEW

**Comment by christophstrobl** [comment]
The mentioned PR has been merged to _main_ and _backported_ to 3.0.x.

**Comment by wilkinsona** [comment]
Please run `./gradlew updateInfrastructure` and add the resulting changes to this PR.

**Comment by wilkinsona** [comment]
Sorry. Please ignore the above. There's no new module here so there are no infra changes to make.

**Comment by christophstrobl** [comment]
2 more weeks should be fine, we'd still have enough time to revisit the issue if something (expectedly) breaks. Same for #161 .

**Comment by christophstrobl** [comment]
Boot already picked up the Spring Data BOM for 2022.0.5 (spring-projects/spring-boot#34903). Please let me know if there's anything I can help with.

**Comment by wilkinsona** [comment]
Thanks for the nudge, Christoph.

**Pull request closed without merging**
