### PR TITLE
Add data-jpa test that uses AbstractPersistable

### PR DESCRIPTION
**Pull request by christophstrobl**
Add reproducer for spring-projects/spring-data-jpa#2735. 
Will fail with an exception like below until spring-projects/spring-data-jpa#2737 is merged to _main_.
```
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'entityManagerFactory': Entity 'com.example.data.jpa.model.Publisher' has no identifier (every '@Entity' class must declare or inherit at least one '@Id' or '@EmbeddedId' property)
```

### CODE REVIEW

**Comment by gregturn** [comment]
https://github.com/spring-projects/spring-data-jpa/issues/2735 has been merged to Spring Data JPA `main` and backported to `3.0.x`. Feel free to move forward on your AOT smoke tests.

**Comment by wilkinsona** [comment]
Please run ./gradlew updateInfrastructure and add the resulting changes to this PR.

**Comment by christophstrobl** [comment]
Rebased on current _main_. 
`./gradlew updateInfrastructure` did not add any changes.

**Comment by wilkinsona** [comment]
Ah, sorry. There's no new module here so there are no infra changes to make.

**Comment by wilkinsona** [comment]
Blocked until Boot has moved to Spring Data snapshots.

**Pull request closed without merging**
