### PR TITLE
Enhance cloud-stream-rabbit/kafka tests

### PR DESCRIPTION
**Pull request by onobc**
- Add multi-binder with complex property for rabbit
- Add complex property for kafka

**[DependsOn]** https://github.com/spring-cloud/spring-cloud-stream/pull/2712

See https://github.com/spring-cloud/spring-cloud-stream/issues/2690

cc: @sobychacko

### CODE REVIEW

**Comment by wilkinsona** [comment]
What's the status of this, @onobc? The title marks it as a work in progress but it looks like the PR that it depends upon has been merged. Can this PR be merged now too?

**Comment by onobc** [comment]
@wilkinsona it dropped off my radar. I will take a look w/in the next 12hrs and let you know the status. Thanks for the ping.

**Comment by onobc** [comment]
@wilkinsona 

- rebased
- ran `:integration:spring-kafka:build`  and `integration:spring-amqp-rabbit:build` with success

Should be ready for review/merge.

**Comment by wilkinsona** [comment]
Thanks, @onobc. What branches can this go in? https://github.com/spring-cloud/spring-cloud-stream/commit/3990bb485e63a86df8a074e8034a74b11a29cc4b went in Spring Cloud Stream 4.0.x so it looks like it could go right the way back to 3.0.x, correct?

**Comment by wilkinsona** [comment]
All good. Thanks, @onobc. This is now in 3.0.x and merged forwards through 3.1.x, 3.2.x, and into main.

**Pull request closed without merging**
