### PR TITLE
Add ldap-odm sample

### PR DESCRIPTION
**Pull request by marcusdacoregio**
Closes gh-88

### CODE REVIEW

**Comment by marcusdacoregio** [comment]
Closing for now while pushing the runtime hints in Spring LDAP

**Comment by snicoll** [comment]
@marcusdacoregio the sample fails atm. I assume this is to be expected? It's not clear from the description so I want to make sure.

**Comment by marcusdacoregio** [comment]
Hi @snicoll, the sample was running fine yesterday. I will check it.

**Comment by snicoll** [comment]
There's a hint in the sample that should move either to the lib directly or to the reachability repo metadata.

**Pull request closed without merging**
