### PR TITLE
Add test for data-redis Jackson2 backed hash mapper.

### PR DESCRIPTION
**Pull request by christophstrobl**
Data Redis `HashMapper` relies on internal Jackson2 node `_value`.

Related to: spring-projects/spring-data-redis#2838 (Tests will break until resolved)

### CODE REVIEW

**Comment by wilkinsona** [comment]
Can this be merged now, @christophstrobl?

**Comment by christophstrobl** [comment]
@wilkinsona let me rebase and check if everything works as expected. will report back once done.

**Comment by christophstrobl** [comment]
rebased, tests passed. should be good now.

**Comment by mhalbritter** [comment]
Merged in https://github.com/spring-projects/spring-aot-smoke-tests/commit/3892b5bfa67bb8fcf3613809b7afe70c26e0fa9b. Thanks Christoph!

**Pull request closed without merging**
